<?xml version="1.0"?>

<!DOCTYPE pizza [
	<!ELEMENT tms (database, logs)>

	<!ELEMENT database (dbdriver, dburl, dbuser, dbpasswd, dbminconn, dbmaxconn)>
	<!ELEMENT dbdriver (#PCDATA)>
	<!ELEMENT dburl (#PCDATA)>
	<!ELEMENT dbuser (#PCDATA)>
	<!ELEMENT dbpasswd (#PCDATA)>
	<!ELEMENT dbminconn (#PCDATA)>
	<!ELEMENT dbmaxconn (#PCDATA)>

	<!ELEMENT logs (logconn, logsize)>
	<!ELEMENT logconn (#PCDATA)>
	<!ELEMENT logsize (#PCDATA)>

	<!ELEMENT format (fordate, fordecimal, forcurrency)>
	<!ELEMENT fordate (#PCDATA)>
	<!ELEMENT fordecimal (#PCDATA)>
	<!ELEMENT forcurrency (#PCDATA)>

]>

<tms>
	<!-- 
	  database configuration 
          <database>
          
               
                <dbdriver>com.mysql.jdbc.Driver</dbdriver>
		<dburl>jdbc:mysql://192.168.16.110:3308/hairisma_mm</dburl>  
                <dbuser>opie</dbuser>
		<dbpasswd>opie</dbpasswd>
		<dbminconn>1</dbminconn>
		<dbmaxconn>1</dbmaxconn>
                
         <dbdriver>com.mysql.jdbc.Driver</dbdriver>
		<dburl>jdbc:mysql://localhost:3309/hairisma_bpd</dburl>  
                <dbuser>root</dbuser>
		<dbpasswd>12345</dbpasswd>
		<dbminconn>1</dbminconn>
		<dbmaxconn>2</dbmaxconn>
                
	</database>	  
	-->	
       <database>
                <dbdriver>com.mysql.jdbc.Driver</dbdriver>
		<dburl>jdbc:mysql://localhost:3306/hairisma_dkph</dburl>  
                <dbuser>root</dbuser>
		<dbpasswd>root12345</dbpasswd>
		<dbminconn>1</dbminconn>
		<dbmaxconn>2</dbmaxconn>
      </database>
	
	<!-- 
	  @logconn	 	- file name that contain application log/history
	  @logsize		- maximum size of log file, in MB
	-->
	<logs>
		<logconn>tmsconn.log</logconn>
		<logapp>tmsapp.log</logapp>
		<logsize>5</logsize>
	</logs>

	<format>
		<fordate>MMM-dd-yyyy</fordate>
		<fordecimal>###,###.############</fordecimal>
		<forcurrency>###,###.00</forcurrency>
	</format>

</tms>
